
# Databricks notebook source
# ============================================================
# Cloud Election Sentinel - Databricks Job liviano
# Simula actualización de conteo electoral cada 15 minutos.
# Python + Supabase/PostgreSQL. Sin IA, sin pandas, sin numpy.
# ============================================================

# IMPORTANTE:
# 1) Evita instalar librerías pesadas en cada ejecución del job.
# 2) En Databricks, instala psycopg2-binary y toml como librerías del cluster/job.
# 3) Si tu docente te exige instalar desde el notebook, descomenta estas 2 líneas:
# %pip install -q psycopg2-binary toml
# dbutils.library.restartPython()

import os
import random
from datetime import datetime, timezone
from decimal import Decimal

import toml
import psycopg2


# ============================================================
# 1. Parámetros del job
# ============================================================

def get_widget_or_default(name: str, default: str) -> str:
    try:
        dbutils.widgets.text(name, default)
        return dbutils.widgets.get(name)
    except Exception:
        return os.getenv(name.upper(), default)


FORCE_RUN = get_widget_or_default("force_run", "false").lower() == "true"
SECRETS_PATH = get_widget_or_default("secrets_path", "secrets.toml")

# Si quieres controlar qué tanto crece en cada corrida:
MIN_FACTOR = float(get_widget_or_default("min_factor", "0.004"))
MAX_FACTOR = float(get_widget_or_default("max_factor", "0.018"))


# ============================================================
# 2. Leer credenciales
# ============================================================

def load_postgres_config():
    """
    Prioridad:
    1. Variables de entorno de Databricks.
    2. Archivo secrets.toml.
    """
    env_user = os.getenv("POSTGRES_USER")
    env_password = os.getenv("POSTGRES_PASSWORD")
    env_host = os.getenv("POSTGRES_HOST")
    env_port = os.getenv("POSTGRES_PORT", "5432")
    env_dbname = os.getenv("POSTGRES_DBNAME", "postgres")

    if env_user and env_password and env_host:
        return {
            "USER": env_user,
            "PASSWORD": env_password,
            "HOST": env_host,
            "PORT": env_port,
            "DBNAME": env_dbname,
        }

    secrets = toml.load(SECRETS_PATH)["postgres"]
    return {
        "USER": secrets["USER"],
        "PASSWORD": secrets["PASSWORD"],
        "HOST": secrets["HOST"],
        "PORT": str(secrets.get("PORT", "5432")),
        "DBNAME": secrets.get("DBNAME", "postgres"),
    }


def get_connection():
    cfg = load_postgres_config()
    return psycopg2.connect(
        user=cfg["USER"],
        password=cfg["PASSWORD"],
        host=cfg["HOST"],
        port=cfg["PORT"],
        dbname=cfg["DBNAME"],
        sslmode="require",
        connect_timeout=10,
    )


# ============================================================
# 3. DDL: tablas necesarias
# ============================================================

DDL = """
CREATE TABLE IF NOT EXISTS candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT NOT NULL UNIQUE,
    partido TEXT,
    orden INTEGER,
    color_hex TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region TEXT NOT NULL,
    provincia TEXT NOT NULL,
    distrito TEXT NOT NULL,
    lugar_votacion TEXT NOT NULL,
    total_actas INTEGER NOT NULL,
    actas_contabilizadas INTEGER NOT NULL DEFAULT 0,
    actas_pendientes INTEGER NOT NULL DEFAULT 0,
    avance_pct NUMERIC(6,2) NOT NULL DEFAULT 0,
    velocidad_actas_h NUMERIC(10,2) NOT NULL DEFAULT 0,
    estado_conteo TEXT NOT NULL DEFAULT 'Sin información',
    color_estado TEXT NOT NULL DEFAULT 'gris',
    motivo_retraso TEXT,
    detalle_retraso TEXT,
    updated_at TIMESTAMPTZ DEFAULT now(),
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(region, provincia, distrito, lugar_votacion)
);

CREATE TABLE IF NOT EXISTS vote_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(id) ON DELETE CASCADE,
    candidate_id BIGINT NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
    votos BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE(location_id, candidate_id)
);

CREATE TABLE IF NOT EXISTS event_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(),
    tipo TEXT NOT NULL,
    evento TEXT NOT NULL,
    detalle TEXT,
    region TEXT,
    provincia TEXT,
    distrito TEXT
);

CREATE TABLE IF NOT EXISTS job_executions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_slot TEXT NOT NULL UNIQUE,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(),
    registros_actualizados INTEGER NOT NULL DEFAULT 0,
    actas_nuevas INTEGER NOT NULL DEFAULT 0,
    estado TEXT NOT NULL,
    detalle TEXT
);
"""


# ============================================================
# 4. Data base simulada
# ============================================================

CANDIDATES = [
    ("Keiko Fujimori", "Fuerza Popular", 1, "#123C7C"),
    ("Roberto Sánchez", "Juntos por el Perú", 2, "#1E63C9"),
    ("Rafael López Aliaga", "Renovación Popular", 3, "#82BFE3"),
    ("César Acuña", "Alianza Popular", 4, "#8AC5E8"),
    ("Fernando Olivera", "Obras por el Perú", 5, "#93CAE8"),
    ("George Forsyth", "País para Todos", 6, "#9BD0EC"),
    ("Alfredo Barnechea", "Acción Popular", 7, "#A5D6EF"),
]

LOCATIONS = [
    # region, provincia, distrito, lugar, total_actas
    ("Lima", "Lima", "Miraflores", "IE Juana Alarco de Dammert", 780),
    ("Lima", "Lima", "San Juan de Lurigancho", "IE Antenor Orrego", 1250),
    ("Lima", "Lima", "Comas", "IE Estados Unidos", 980),

    ("Arequipa", "Arequipa", "Cercado", "IE Independencia Americana", 620),
    ("Arequipa", "Caylloma", "Chivay", "IE Francisco García Calderón", 280),

    ("La Libertad", "Trujillo", "Trujillo", "IE San Juan", 720),
    ("La Libertad", "Sánchez Carrión", "Huamachuco", "IE César Vallejo", 330),

    ("Piura", "Piura", "Castilla", "IE Miguel Cortés", 610),
    ("Piura", "Ayabaca", "Ayabaca", "IE Señor Cautivo", 260),

    ("Cusco", "Cusco", "Wanchaq", "IE Garcilaso de la Vega", 540),
    ("Cusco", "La Convención", "Santa Ana", "IE Manco II", 310),

    ("Puno", "Puno", "Puno", "IE Gran Unidad San Carlos", 470),
    ("Puno", "Azángaro", "Azángaro", "IE INA 21", 230),
    ("Puno", "Carabaya", "Macusani", "IE Agropecuario", 190),

    ("Huancavelica", "Huancavelica", "Ascensión", "IE La Victoria de Ayacucho", 210),
    ("Huancavelica", "Tayacaja", "Pampas", "IE Daniel Hernández", 170),

    ("Amazonas", "Chachapoyas", "Chachapoyas", "IE Seminario Jesús María", 200),
    ("Amazonas", "Condorcanqui", "Nieva", "IE Nieva", 130),

    ("Apurímac", "Abancay", "Abancay", "IE Miguel Grau", 250),
    ("Apurímac", "Andahuaylas", "Talavera", "IE José María Arguedas", 190),

    ("Ucayali", "Coronel Portillo", "Callería", "IE Faustino Maldonado", 420),
    ("Ucayali", "Atalaya", "Raimondi", "IE Francisco Bolognesi", 150),
]

# Velocidad esperada por región. Menor factor = avance más lento.
REGION_SPEED_FACTOR = {
    "Lima": 1.60,
    "Arequipa": 1.20,
    "La Libertad": 1.15,
    "Piura": 1.05,
    "Cusco": 0.90,
    "Puno": 0.45,
    "Huancavelica": 0.42,
    "Amazonas": 0.38,
    "Apurímac": 0.50,
    "Ucayali": 0.40,
}

# Probabilidad de incidencia por región.
REGION_INCIDENT_PROB = {
    "Lima": 0.03,
    "Arequipa": 0.05,
    "La Libertad": 0.06,
    "Piura": 0.08,
    "Cusco": 0.12,
    "Puno": 0.35,
    "Huancavelica": 0.38,
    "Amazonas": 0.42,
    "Apurímac": 0.30,
    "Ucayali": 0.36,
}

INCIDENTS_BY_REGION = {
    "Puno": [
        ("Corte eléctrico intermitente", "Interrupciones de energía en centros de acopio reducen la velocidad de registro y validación de actas."),
        ("Traslado de material electoral", "La distancia entre locales de votación rurales y centros de procesamiento retrasa el ingreso de nuevas actas."),
        ("Conectividad limitada", "La transmisión de información presenta demoras por baja estabilidad de red en zonas alejadas."),
    ],
    "Huancavelica": [
        ("Condición de ruta", "Las rutas de acceso presentan demoras logísticas, reduciendo la llegada de actas al centro de procesamiento."),
        ("Validación manual adicional", "Un grupo de actas requiere revisión operativa antes de su contabilización."),
        ("Conectividad intermitente", "El registro se retrasa por cortes de comunicación en puntos de acopio."),
    ],
    "Amazonas": [
        ("Traslado fluvial o rural", "La dispersión geográfica de locales de votación retrasa el traslado de documentación electoral."),
        ("Demora logística", "La recolección de actas avanza por lotes pequeños debido a limitaciones de transporte."),
        ("Conectividad limitada", "La carga de información se realiza de forma parcial por disponibilidad irregular de red."),
    ],
    "Ucayali": [
        ("Transporte fluvial", "Algunas actas dependen de rutas fluviales, lo que genera retrasos en su llegada al punto de registro."),
        ("Conectividad intermitente", "La transmisión de datos se realiza de forma irregular por cobertura limitada."),
        ("Demora logística", "El ingreso de actas avanza por tandas debido a la distancia entre centros poblados."),
    ],
    "Apurímac": [
        ("Condición de ruta", "La geografía de la zona genera demoras en el traslado de material electoral."),
        ("Carga acumulada", "El centro de procesamiento presenta acumulación temporal de actas pendientes."),
    ],
    "Cusco": [
        ("Traslado desde zonas rurales", "El ingreso de actas rurales se produce con menor velocidad que en zonas urbanas."),
        ("Validación operativa", "Algunas actas requieren validación previa antes de ser contabilizadas."),
    ],
    "default": [
        ("Carga operativa temporal", "El centro de procesamiento recibió más actas de lo habitual y el registro avanza por lotes."),
        ("Validación manual adicional", "Algunas actas requieren revisión antes de ser contabilizadas."),
        ("Sin incidencia crítica", "El avance se mantiene dentro del comportamiento esperado del proceso."),
    ],
}


# ============================================================
# 5. Funciones auxiliares
# ============================================================

def current_15_min_slot() -> str:
    now = datetime.now(timezone.utc)
    minute_slot = (now.minute // 15) * 15
    slot = now.replace(minute=minute_slot, second=0, microsecond=0)
    return slot.strftime("%Y-%m-%dT%H:%M:%SZ")


def setup_database(conn):
    with conn.cursor() as cur:
        cur.execute(DDL)
    conn.commit()


def seed_base_data(conn):
    with conn.cursor() as cur:
        for nombre, partido, orden, color_hex in CANDIDATES:
            cur.execute("""
                INSERT INTO candidates (nombre, partido, orden, color_hex)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (nombre) DO UPDATE SET
                    partido = EXCLUDED.partido,
                    orden = EXCLUDED.orden,
                    color_hex = EXCLUDED.color_hex
            """, (nombre, partido, orden, color_hex))

        for region, provincia, distrito, lugar, total_actas in LOCATIONS:
            # Carga inicial: entre 8% y 22% para que el dashboard no empiece vacío.
            initial_count = int(total_actas * random.uniform(0.08, 0.22))
            pendientes = total_actas - initial_count
            avance = round((initial_count / total_actas) * 100, 2)

            cur.execute("""
                INSERT INTO locations (
                    region, provincia, distrito, lugar_votacion,
                    total_actas, actas_contabilizadas, actas_pendientes,
                    avance_pct, velocidad_actas_h, estado_conteo, color_estado,
                    motivo_retraso, detalle_retraso, updated_at
                )
                VALUES (%s, %s, %s, %s, %s, %s, %s, %s, 0, 'Avance inicial', 'amarillo',
                        'Carga inicial simulada',
                        'Se registra una base inicial para iniciar el monitoreo del conteo.',
                        now())
                ON CONFLICT (region, provincia, distrito, lugar_votacion) DO NOTHING
            """, (region, provincia, distrito, lugar, total_actas, initial_count, pendientes, avance))

    conn.commit()


def already_executed(conn, run_slot: str) -> bool:
    with conn.cursor() as cur:
        cur.execute("SELECT 1 FROM job_executions WHERE run_slot = %s", (run_slot,))
        return cur.fetchone() is not None


def get_candidates(conn):
    with conn.cursor() as cur:
        cur.execute("SELECT id, nombre, orden FROM candidates ORDER BY orden")
        return cur.fetchall()


def get_locations(conn):
    with conn.cursor() as cur:
        cur.execute("""
            SELECT id, region, provincia, distrito, lugar_votacion,
                   total_actas, actas_contabilizadas
            FROM locations
            WHERE actas_contabilizadas < total_actas
            ORDER BY region, provincia, distrito
        """)
        return cur.fetchall()


def choose_incident(region: str):
    options = INCIDENTS_BY_REGION.get(region, INCIDENTS_BY_REGION["default"])
    return random.choice(options)


def classify_status(region: str, avance_pct: float, new_actas: int, speed_h: float, has_incident: bool):
    """
    Reglas simples para pintar el estado:
    - rojo: avance muy bajo + poca actualización + incidencia.
    - naranja: avance bajo o velocidad baja.
    - verde: avance normal.
    """
    if has_incident and (new_actas <= 3 or speed_h < 20) and avance_pct < 85:
        return "Retraso crítico", "rojo"

    if new_actas <= 5 and avance_pct < 90:
        return "Avance bajo", "naranja"

    if speed_h < 30 and avance_pct < 90:
        return "Avance bajo", "naranja"

    if avance_pct >= 95:
        return "Avance alto", "verde"

    return "Avance normal", "verde"


def distribute_votes(new_actas: int, candidates_count: int, region: str):
    """
    Convierte nuevas actas en votos simulados.
    No usa IA. Solo distribución porcentual con pequeña variación regional.
    """
    if new_actas <= 0:
        return [0] * candidates_count

    voters_per_acta = random.randint(170, 260)
    total_votes = new_actas * voters_per_acta

    # Base parecida al ejemplo visual, pero con ruido.
    base = [0.285, 0.187, 0.162, 0.134, 0.089, 0.063, 0.045]
    base = base[:candidates_count]

    # Ajustes regionales simulados para que no todo sea igual.
    if region in ("Puno", "Cusco", "Apurímac", "Huancavelica"):
        if candidates_count > 1:
            base[1] += 0.035
            base[0] -= 0.020
    if region in ("Lima", "Arequipa"):
        base[0] += 0.020
        if candidates_count > 3:
            base[3] -= 0.010
    if region in ("Ucayali", "Amazonas"):
        if candidates_count > 5:
            base[5] += 0.025
            base[2] -= 0.010

    # Ruido controlado
    noisy = []
    for p in base:
        noisy.append(max(0.01, p + random.uniform(-0.012, 0.012)))

    total_p = sum(noisy)
    normalized = [p / total_p for p in noisy]

    votes = [int(total_votes * p) for p in normalized]
    diff = total_votes - sum(votes)
    if votes:
        votes[0] += diff

    return votes


def update_one_location(conn, loc, candidates):
    location_id, region, provincia, distrito, lugar, total_actas, current_count = loc

    remaining = total_actas - current_count
    if remaining <= 0:
        return 0

    speed_factor = REGION_SPEED_FACTOR.get(region, 0.85)
    incident_prob = REGION_INCIDENT_PROB.get(region, 0.10)
    has_incident = random.random() < incident_prob

    # Cantidad de actas nuevas para esta ejecución de 15 minutos.
    raw_increment = int(total_actas * random.uniform(MIN_FACTOR, MAX_FACTOR) * speed_factor)

    if has_incident:
        # Si hay incidencia, el ingreso baja fuerte.
        raw_increment = int(raw_increment * random.uniform(0.10, 0.40))

    # Evitar incrementos enormes y mantener simulación realista.
    new_actas = max(0, min(remaining, raw_increment))

    # Para zonas normales, evitar que siempre sea 0.
    if not has_incident and remaining > 0:
        new_actas = max(1, new_actas)

    updated_count = current_count + new_actas
    pending = total_actas - updated_count
    avance_pct = round((updated_count / total_actas) * 100, 2)
    speed_h = round(new_actas * 4, 2)  # porque cada corrida representa 15 min.

    if has_incident:
        motivo, detalle = choose_incident(region)
    else:
        motivo = "Sin incidencia crítica"
        detalle = "El conteo avanza dentro del ritmo esperado para la zona."

    estado, color = classify_status(region, avance_pct, new_actas, speed_h, has_incident)

    with conn.cursor() as cur:
        cur.execute("""
            UPDATE locations
            SET actas_contabilizadas = %s,
                actas_pendientes = %s,
                avance_pct = %s,
                velocidad_actas_h = %s,
                estado_conteo = %s,
                color_estado = %s,
                motivo_retraso = %s,
                detalle_retraso = %s,
                updated_at = now()
            WHERE id = %s
        """, (
            updated_count, pending, avance_pct, speed_h,
            estado, color, motivo, detalle, location_id
        ))

        votes = distribute_votes(new_actas, len(candidates), region)
        for idx, candidate in enumerate(candidates):
            candidate_id = candidate[0]
            votos = votes[idx] if idx < len(votes) else 0
            cur.execute("""
                INSERT INTO vote_results (location_id, candidate_id, votos, updated_at)
                VALUES (%s, %s, %s, now())
                ON CONFLICT (location_id, candidate_id)
                DO UPDATE SET
                    votos = vote_results.votos + EXCLUDED.votos,
                    updated_at = now()
            """, (location_id, candidate_id, votos))

        if estado in ("Retraso crítico", "Avance bajo"):
            cur.execute("""
                INSERT INTO event_logs (fecha_hora, tipo, evento, detalle, region, provincia, distrito)
                VALUES (now(), %s, %s, %s, %s, %s, %s)
            """, (
                "Alerta",
                f"{estado} detectado en {region} - {distrito}",
                f"{motivo}. {detalle} Último ingreso: {new_actas} actas. Avance: {avance_pct}%.",
                region, provincia, distrito
            ))

    return new_actas


def insert_job_execution(conn, run_slot: str, updated_locations: int, total_new_actas: int, estado: str, detalle: str):
    with conn.cursor() as cur:
        cur.execute("""
            INSERT INTO job_executions (run_slot, fecha_hora, registros_actualizados, actas_nuevas, estado, detalle)
            VALUES (%s, now(), %s, %s, %s, %s)
            ON CONFLICT (run_slot) DO NOTHING
        """, (run_slot, updated_locations, total_new_actas, estado, detalle))

        cur.execute("""
            INSERT INTO event_logs (fecha_hora, tipo, evento, detalle)
            VALUES (now(), %s, %s, %s)
        """, (
            "Job Databricks",
            "Actualización simulada de conteo electoral",
            f"Slot: {run_slot}. Lugares actualizados: {updated_locations}. Actas nuevas: {total_new_actas}."
        ))


# ============================================================
# 6. Ejecución principal
# ============================================================

def main():
    run_slot = current_15_min_slot()
    print(f"Inicio del job Cloud Election Sentinel. Slot: {run_slot}. FORCE_RUN={FORCE_RUN}")

    # Semilla por slot para evitar comportamiento completamente errático.
    random.seed(run_slot)

    conn = get_connection()

    try:
        setup_database(conn)
        seed_base_data(conn)

        if already_executed(conn, run_slot) and not FORCE_RUN:
            print(f"El slot {run_slot} ya fue ejecutado. No se inserta data duplicada.")
            return

        candidates = get_candidates(conn)
        locations = get_locations(conn)

        updated_locations = 0
        total_new_actas = 0

        for loc in locations:
            new_actas = update_one_location(conn, loc, candidates)
            if new_actas >= 0:
                updated_locations += 1
                total_new_actas += new_actas

        insert_job_execution(
            conn,
            run_slot=run_slot,
            updated_locations=updated_locations,
            total_new_actas=total_new_actas,
            estado="OK",
            detalle="Actualización simulada ejecutada correctamente desde Databricks."
        )

        conn.commit()

        print("✅ Job finalizado correctamente.")
        print(f"Registros actualizados: {updated_locations}")
        print(f"Actas nuevas simuladas: {total_new_actas}")

    except Exception as e:
        conn.rollback()
        print(f"❌ Error en el job: {str(e)}")
        try:
            insert_job_execution(
                conn,
                run_slot=run_slot,
                updated_locations=0,
                total_new_actas=0,
                estado="ERROR",
                detalle=str(e)[:500]
            )
            conn.commit()
        except Exception:
            pass
        raise

    finally:
        conn.close()


main()
