-- ==========================================================
-- Cloud Election Sentinel - DDL Supabase PostgreSQL
-- Proyecto: dashboard tipo ONPE en Streamlit + Supabase
-- ==========================================================

CREATE TABLE IF NOT EXISTS candidates (
    candidate_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_name TEXT NOT NULL,
    party_name TEXT NOT NULL,
    party_symbol TEXT,
    display_color TEXT DEFAULT '#0B4EA2',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region TEXT NOT NULL,
    province TEXT NOT NULL,
    district TEXT NOT NULL,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    total_actas INTEGER NOT NULL DEFAULT 0,
    actas_contabilizadas INTEGER NOT NULL DEFAULT 0,
    actas_pendientes INTEGER NOT NULL DEFAULT 0,
    actas_observadas INTEGER NOT NULL DEFAULT 0,
    velocidad_actas_hora NUMERIC(10,2) NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS vote_results (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id BIGINT NOT NULL REFERENCES locations(location_id) ON DELETE CASCADE,
    candidate_id BIGINT NOT NULL REFERENCES candidates(candidate_id) ON DELETE CASCADE,
    valid_votes INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now(),
    CONSTRAINT uq_vote_location_candidate UNIQUE (location_id, candidate_id)
);

CREATE TABLE IF NOT EXISTS event_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_time TIMESTAMPTZ DEFAULT now(),
    event_type TEXT NOT NULL,
    event_name TEXT NOT NULL,
    detail TEXT
);

CREATE INDEX IF NOT EXISTS idx_locations_region ON locations(region);
CREATE INDEX IF NOT EXISTS idx_locations_province ON locations(province);
CREATE INDEX IF NOT EXISTS idx_locations_district ON locations(district);
CREATE INDEX IF NOT EXISTS idx_vote_results_location ON vote_results(location_id);
CREATE INDEX IF NOT EXISTS idx_vote_results_candidate ON vote_results(candidate_id);
CREATE INDEX IF NOT EXISTS idx_event_logs_time ON event_logs(event_time DESC);
